### PR TITLE
NGINX Support in install script for devmaster server.

### PR DESCRIPTION
**Pull request by jonpugh**
Thanks to the efforts of @arosboro we're looking to get nginx support into the devshop scripts.

It's always been possible to do it manually by setting up remote servers with nginx, but still a bit of a hassle.

Let's do this!

P.S. We should probably make this the default! It seems a lot faster on my local VM.

After this is complete we should add NGINX as an option in the `devshop remote:install` command.

### CODE REVIEW

**Comment by jonpugh** [comment]
This *almost* works!

For some reason, it is still installing apache, which takes over port 80.

Install this branch, then:

```
apt-get remove apache2 --purge
service nginx restart
```

And devmaster will work.

I had a problem with environment URLs, but I think all I have to do is remove the default NGINX config.

**Comment by jonpugh** [comment]
IT WORKS

**Comment by jonpugh** [comment]
Ok, so php5 installs apache!  HUGE thanks to @arosboro for the tip to switch the package name.

I also had to fix bug in devshop_provision that I made that added bad NGINX config, like a long time ago!  Ooops :(

So that means that NGINX hasn't  worked with devshop since I added those environment variables, which makes me sad.  I really should have done this a long time ago!

At least we can do a big announcement about it now :D

**Comment by jonpugh** [comment]
I am going to run an install using centos now to enasure it works on RHEL family.

**Comment by arosboro** [comment]
I did some testing this morning deploying on a physical server in the cloud.  Ubuntu 15.10 does not install devmaster cleanly.  Switched to Ubuntu 14.04 and everything went smoothly.

**Comment by jonpugh** [comment]
Yes, we can't support non LTS releases on Ubuntu yet, there's simply too many variants in between them to cover them all.

I ran out of steam last night but am almost through verifying that it works on centos7.  

Once it does, I'm merging it!

**Comment by arosboro** [comment]
Yes I barely had enough juice left to find a solution for passing the checks while I made dinner.  Don't feel you have to work long hours on my account.  I have a unique situation in that my apartment is directly above our office, and it's easy for me to do work related tasks while still being able to step away and take care of the essentials.  

I provisioned a server on the pr-nginx branch and am looking at devshop-cloud w/ a  working copy of that branch in my devmaster profile today.

**Comment by jonpugh** [comment]
So the install passes now, but loading the devshop.site page gives me the NGINX 502 bad gateway...

@arosboro said he'd take a look!

**Comment by jonpugh** [comment]
Ah I forgot to mention...

In CentoOS 7, the stock /etc/nginx/nginx.conf has an entry that conflicted with Aegir's:

I had to comment it out to get nginx to start:

```
#    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
#                      '$status $body_bytes_sent "$http_referer" '
#                      '"$http_user_agent" "$http_x_forwarded_for"';

#    access_log  /var/log/nginx/access.log  main;
```

**Comment by arosboro** [comment]
How would I comment this out, with an nginx.conf.Redhat.j2 template?

**Comment by jonpugh** [comment]
My plan is to eventually port everything to use standard ansible roles for things like NGINX.

Let's try to do everything with an eye towards that: https://github.com/geerlingguy/ansible-role-nginx

**Comment by jonpugh** [comment]
Just merged in from 0.x, which includes the new travis testing!

**Comment by jonpugh** [comment]
:white_check_mark:

**Comment by jonpugh** [comment]
Amazing work, @arosboro !!!

One LAST request before merging: Could you add a documentation page on NGINX? Once we have that, I'll merge it!

**Comment by jonpugh** [comment]
eh, forget it!  Let's do this!

**Pull request merged**
