### PR TITLE
Use core DevShop source for DevShop Control site.

### LINKED ISSUE #313: Platform verification fails if drush is installed via composer at project level
When drush is installed locally as part of the project, platform verification fails because the corresponding alias cannot be found. The command executed is:

```
/var/aegir/projects/[projectname]/dev/web/../vendor/bin//drush --backend=2 @platform_[project]_dev provision-verify 2>&1
```

```
The command could not be executed successfully (returned: [preflight] The alias @platform_[project]_dev could not be found. , code: 0)
```

I had to remove locally installed drush for it to pass, but I use locally installed drush in my local environment. Any ideas or workaround?

### LINKED ISSUE #644: Use the core devshop codebase for the DevShop Control site
In the install-sh PR (#631) I made a drastic change to remove a root cause of a ton of instability: Using a separate git repo for devmaster and devshop_control was not testable, because the git commits would be different.

I realized that the changes I've made to provision and hosting_platform to store git_root and git_docroot separately actually allow for using the devshop repo itself as a Drupal site codebase!

This PR cherry-picks those changes.

- [ ] Change `devshop_control` variables to point to `devshop_cli_path` and alter the docroot/publish path values to match the current location.
- [ ] Ensure aegir owns the devshop_control root and all files.
- [ ] Put the local repository back for drupal/devmaster: Every devshop_control site should use a "path" repo (symlinked to /usr/share/devshop) by default. Implementors of `devshop/control-template` can remove this path repo and install with composer normally as needed.

### PR DESCRIPTION
**Pull request by jonpugh**
Resolves #644 

This will also help forked PRs like #641 , as it will allow in-source devmaster installs.

### Follow up tasks

- [x] Replace devmaster not found error message with a thrown exception so composer command fails with exit 1.
- [x] Rename "DevShopControlTemplate" to "DevShopControlProject" and `devshop/control-template` to `devshop/control-template`.
- [x] Update docs of DevShopControl README.md to explain what the default is and what the project can do.
- [x] Check that provision logging looks good in front-end.
- [x] Use post-project-create to remove the custom path repository for devmaster in composer.json.
- [x] Update Documentation to clarify Devmaster vs DevShop Control.
- [x] Ensure `devshop/control-project` works independently.
- [x] Separate DevShopControl Core from the Control Project template!
- [x] Rename `DevShopControlProject` to just `ControlProject`.
- [x] Tag new alpha releases of `drupal/provision` and `drupal/hosting`.
- [x] Pin provision and hosting versions to Control's .lock file and ControlProject's .json file.
- [x] Add all supported PHP versions to the test matrix.
- [ ] **MERGE THIS PR (#645)**

### 1.7.0 alpha release blockers:
- [ ] Install.sh improvements. #631 
- [ ] Add a .lando.yml file so the DevShop Control front end can be developed in lando.
- [ ] See if we can move provision and drush 8 to the Control stack so we can... GASP remove drush 8 from global namespace! This might fix #313

- [ ] Update composer packages to match latest recommended and passing packages.
- [ ] Improve dev/no-dev, minimum stability, etc and learn from drupal core project-recommmended and others to improve the composer experience.
- [ ] Figure out why --prefer-source and (maybe?) --no-dev are needed.
- [ ] Fix Remote PRs: #641 
- [ ] Improve testing and test-artifact generation:
  - [ ] Save screenshots.
  - [ ] Save test command logs to files.
- [ ] After merge to 1.x, ensure the 1.x tests run and pass, check docker images.
- [ ] Fast Docker playbook.
- [ ] Ansible Role updater.
- [ ] Aegir Ansible server management. (Can root be made to run drush @hostmaster hosting-task? If so, ansible tasks as root can be done, allowing web based server config via ansible vars and roles.
- [ ] Provision verify must trigger update hooks on git update.
- [ ] Update "deploy" task to use provision verify for most git work. Remove "devshop deploy" task.
- [ ] Confirm editing of Aegir site and platform git remote, git reference, etc properly works.

### Commit Message

- DevShop UI and CLI code in one repo:
  - DevShop Control site code is now directly in /usr/share/devshop/src/DevShop/Components/DevShopControlTemplate .
  - DevShop Control Project, customizable composer based devshop front-end is at /usr/share/devshop/src/DevShop/Components/ControlProject:
  - Add the local path composer repository directly to composer.json for stability and easier upgrades, allowing us to remove all the custom repository setting everywhere.
  - Stabilize composer based DevShop Control and DevShop Control Project codebases by matching the command everywhere it is run. Composer update is required for it to work properly because it doesn't have a composer.lock file.
  - Add code to ScriptHandler.php to detect an incorrect install by validating that devmaster.info and views.info are in place, and announce if it is a symlink (path repo).
  - Add a step to prepare the composer.lock file in the DevShop control folder.
  - Grant ownership of the devshopcontrol stack to the aegir user.
- Improve DevShop CI testing:
  - Add testing support for PHP 7.1, 7.2, 7.3 and 7.4 for the components and 7.2 and 7.3 for devshop server.
  - Ensure code is on a branch so devshop version detection is done properly and shows in the logs. 
  - Remove extra github actions prepare script devshop-container-prep.sh because we don't need a custom composer repo or a branch.
  - Make the Test and Build workflows run the same commands, using `git switch --create` to prepare a local branch so devshop thinks it is on a branch version and it's easier to see what version is installed.
  - Fixed artifact saving of docker logs and test failures to github actions.
  - Make sure Build step gets important args as well as Test step.
  - Set all roles to run "always" in devshop.server/play.yml for now, so that everything gets reconfigured at runtime (docker up).
  - Reduce running of roles more than once by removing them from "dependencies" of our other roles.
- Ansible improvements
  - Improve initial install state by stopping supervisor before DevShop Control install and starting it again after hostmaster is ready. This stops the issue of always having to restart supervisor every time you install a server!
  - Log messages showing the version and git URL of devshop that is being installed at the beginning and end of the play.
  - Run the devshop control install as a block so we can print debugging information after the install logs showing version, etc.
  - Fix a bug on initial install by converting `aegir_user_uid_current` ansible variable to string before checking if empty.
  - Add echo of current ansible playbook to `devshop-ansible-playbook` command so we can see what is about to run.
- Provision and Hosting 4.x improvements:
  - Drastically reduce logs on site install failure: Remove print of debug backtrace, call to "dlp", and exit the function so additional steps that assume site install is fine don't keep going. 
  - Completely clean up pre provision verify to allow that single command to handle creation and updating of Git and composer commands.
  - Add more platform properties, git_reset
  - Allow provision-verify to skip git actions such as fetch, checkout, reset with drush options.
  - Allow provision-verify to set the URL of a git remote if '--set-remote' option is used. 
  - Drastically improve logging by detecting if the provision command is being run in CLI or from the hosting_task queue. Logs are now visible from both user experiences.
  - Add git repo helper functions to Provision Platform context class as a bridge before we can integrate GitRepositoryAwareTrait.

### CODE REVIEW

**Review by matthandus — APPROVED** [review]
No obvious code issues. Was able to replicate successful Robo Up on local machine. Nice work!

**Comment by matthandus** [comment]
The TBD info looks good. Not sure we should add it here... but it looks like MySQL Root password still needs work.

**Comment by jonpugh** [comment]
I think the MySQL password being "root" is ok. It's the default for geerlingguy.mysql.

Install.sh creates a password. Anyone installing with just the ansible playbooks would be setting up their own inventory anyway, where they would set their own `mysql_root_password` variable. These users would also probably use ansible secrets or something to secure their root password.

**Comment by jonpugh** [comment]
> Install.sh creates a password.

Hmm so we should make sure only root can read the inventory file it writes?

**Comment by matthandus** [comment]
> > Install.sh creates a password.
> 
> Hmm so we should make sure only root can read the inventory file it writes?

Yes for sure... and the password will need to be encrypted to meet gov security audit.

**Comment by jonpugh** [comment]
Ok, after trying to create a new project from the packagist project `devshop/control-project` it failed because w can't change the path repository.

So I gave in and copied out DevShopControlProject to /src/DevShop/Control. It's better. We can commit the .lock file!

**Comment by matthandus** [comment]
Hi @jonpugh This looks great! I'm pulling in changes and running robo up now.

**Pull request merged**
