### PR TITLE
Ubuntu 16.04 support

### PR DESCRIPTION
**Pull request by jonpugh**
This PR is open for others to contribute to.

The following ansible roles will need work as well...
- http://github.com/opendevshop/ansible-role-aegir-user
- http://github.com/opendevshop/ansible-role-aegir-nginx
- http://github.com/opendevshop/ansible-role-aegir-apache
- http://github.com/opendevshop/ansible-role-devmaster

Please, if you are able, submit Pull requests against this branch.

### CODE REVIEW

**Comment by discipolo** [comment]
here are my notes of changes i made to current 1.x branch to get it installed on xenial
locally verified on vagrant using  "geerlingguy/ubuntu1604" (since current docker setup doesnt deal with systemd)

1. opendevshop.aegir-apache/tasks/Debian.yml
    - name: 'libapache2-mod-php7.0'
2. Roles.yml:

  - name: geerlingguy.php
     version: 3.0.4

  - name: geerlingguy.php-mysql
    version: 2.0.0
3. opendevshop.devmaster/vars/vars.Debian.yml
extra_packages:
  - php7.0
  - php7.0-mcrypt
  - php7.0-cli
  - php7.0-common
  - php7.0-curl
  - php7.0-dev
  - php7.0-fpm
  - php7.0-gd
  - php-pear
  - php-apcu
  - postfix
  - libpcre3-dev
  - vim
  - supervisor
  - openssl


(looks like all generic php packages (instead of php7.0 or php5 ) work fine but during tests i was specific)

4. still looking for the ansible adjustments i had to make for mysql 5.7 changes to user permissions, will add those once i found them

**Comment by arosboro** [comment]
I have some time to review this PR today.  I'll see what I can do to spin up 16.04 since I see php 7 support as an essential item for Drupal 8 projects.

**Comment by jonpugh** [comment]
Awesome news, @arosboro!

I'd look into using the containers to get this working. I am considering dropping support for the Ansible roles and install.sh completely in favor of using Aegir debian pkg.

You should try Robo, http://robo.li. There are robo commands for prepare:containers and `robo up`

**Comment by arosboro** [comment]
Can you give me an idea of what the best practice for deploying to Azure would be?  Was currently considering a 16.04 VM w/ install.sh and some remote vms, but now I'll have to look into robo since I've fallen behind on the current install method recommendations.

**Comment by jonpugh** [comment]
Sorry, didn't mean to discourage you from trying...

Never used azure!

I suppose since that's you're situation, try out install.sh once you've updated the Ansible roles.

**Comment by arosboro** [comment]
Sorry for the errant PR, I've closed that.

@jonpugh I haven't given up.

I included changes to roles.yml according to what you suggested had worked during his testing. There were 2 PRs that had implemented your suggestions favoring generic PHP packages over versioned packages:

opendevshop/ansible-role-devmaster#1
opendevshop/ansible-role-aegir-apache#2

A temporary change to install.sh on line 26 enables this branch for testing.

I tested this script on a VPS host and it successfully installed with 16.04.3.

To replicate with Digital Ocean Fresh VM

1. Set sudo password with `passwd`
2. Change hostname to fqdn, editing `/etc/hostname` (reboot)
3. `cd /root`
4. `wget https://raw.githubusercontent.com/opendevshop/devshop/ubuntu-16/install.sh`
5. `bash install.sh`

**Comment by jonpugh** [comment]
Thanks so much for this work, @arosboro ...

I opened up the roles to look at this again and remembered why I stopped trying with Ansible Galaxy roles.

The roles we chose are not "universal", meaning Ubuntu 14 must use `geerlingguy.php` version 2, Ubuntu 16 must use 17.

This means that we will have to maintain separate `roles.yml` files for each operating system! I thought that using Ansible meant we could abstract the differences between OSs into the playbooks, but now I'm not so sure.

In fact the sheer amount of legwork needed to update a minor thing like adding a package when using so many galaxy roles is unmanageble.  

(figure out which role, create a PR, test it, merge it, release it, check import on galaxy.ansible.com, submit a PR on DevShop roles.yml, set the version, hope that the build completes, go back to the role, edit, push, wait, then re-run devshop repo tests...!!!!) 

If anyone has any thoughts on how to mitigate this issue, I'd love to hear it.

Part of me want to just setup a deb package just like Aegir does it.

**Comment by arosboro** [comment]
Yes, a deb package may be ideal.  I have more experience with ansible and wanted to evaluate Ubuntu 16.04 for a potential project.  I am open to deprecating ansible roles if there is a better way, I was just unfamiliar with the newer setup process.

I agree to have roles in separate repositories and overriding the repository's install.sh is less than desirable when developing and testing.

**Comment by jonpugh** [comment]
Well this is frustrating...

I refactored everything so the modern @geerlingguy's roles work, fixed the centOS test, and the Ubuntu 14 test, but...

Ubuntu16 just HANGS THERE in the middle of the behat test, at the same spot every time: https://travis-ci.org/opendevshop/devshop/jobs/343555834#L2774


I have no idea... the next step is "press Create Projects & Environments". I can't think of a reason this would hang and not fail!

So close... tempted to merge, because at least the other OSes are updated to latest ansible roles.

**Comment by jonpugh** [comment]
I am able to reproduce this on a digital ocean droplet.

Loading the project page `drpl8` in the browser hangs indefinitly.  All other pages seem to work.

**Comment by jonpugh** [comment]
I think it's got something to do with the git status detection.

I'm seeing a lot of open "git" processes for www-data.

**Comment by jonpugh** [comment]
Holy....


[git_status] => On branch master
--
  | Your branch is up-to-date with 'origin/master'.
  | Untracked files:
  | (use "git add <file>..." to include in what will be committed)
  |  
  | [31mdocroot/sites/all/[m
  | [31mdocroot/sites/drpl8.dev.ubuntu16.devshop.systems/[m
  | [31mdocroot/sites/sites.php[m
  |  
  |  
  | It took 13.58 seconds to enumerate untracked files. 'status -uno'
  | may speed it up, but you have to be careful not to forget to add
  | new files yourself (see 'git help status').
  | nothing added to commit but untracked files present (use "git add" to track)

**Comment by jonpugh** [comment]
Even when I removed all the git checking, page loads for drpl8 project with 2 environments is abysmal, and still times out after boots_preprocess_environment().

**Comment by arosboro** [comment]
I also had issue w/ the ssh deploy keys and verify task failing because the ssh auth presented a dialogue confirmation prompt when setting up a project.

**Comment by jonpugh** [comment]
traced it to the environment template... If you comment out the environments theme array blocks it doesn't hang: https://github.com/opendevshop/devmaster/blob/1.x/themes/boots/template.php#L953

**Comment by jonpugh** [comment]
It's hanging somewhere between `boots_preprocess_environment()` and `environment.tpl.php`.

**Comment by jonpugh** [comment]
Wow, that was tricky! Step by step I moved a "return" until it hanged indefinitely... eventually coming down to ae96ff9

**Comment by jonpugh** [comment]
YES Finally.

After figuring out what in devmaster caused the hang, it was still failing in Travis!

This lead me to discover that the robo command was building devmaster in devmaster-1.x always.  

`robo up` ran prepareSource which put the code into devmaster-1.x, when the install.sh script is expecting `devmaster-ubuntu-16`!

So if DEVSHOP_VERSION is set to anything other than 1.x in install.sh it would use `build-devmaster.make` to just use the latest cached dev release of devmaster on drupal.org, which is currently a few days old. 

SO by creating a robo option for `--devshop-version`, we can put the devmaster install in any folder we want.

**Comment by jonpugh** [comment]
It's about to pass...

**Comment by jonpugh** [comment]
Merged!

**Pull request merged**
