### PR TITLE
Switching roles.yml to galaxy names

### PR DESCRIPTION
**Pull request by jonpugh**
This PR is coupled with the efforts to release ansible galaxy playbooks:

- https://galaxy.ansible.com/opendevshop/aegir-apache/
- https://galaxy.ansible.com/opendevshop/aegir-nginx/
- https://galaxy.ansible.com/opendevshop/aegir-user/
- https://galaxy.ansible.com/opendevshop/devmater/

We started tagging those with releases, and keeping the version in `roles.yml`.

### CODE REVIEW

**Comment by jonpugh** [comment]
come on nginx....

**Comment by jonpugh** [comment]
:game_die:

**Comment by jonpugh** [comment]
:game_die: :dash:

**Comment by jonpugh** [comment]
dug up nginx error on local...

```
2016/05/05 13:49:06 [emerg] 23123#0: "server_names_hash_bucket_size" directive is duplicate in /etc/nginx/conf.d/aegir.conf:21

```

**Comment by jonpugh** [comment]
I neglected to replace the part about aegir being in the www-data group :dart:

**Comment by jonpugh** [comment]
I got my local VM with nginx running so ... I'm going to wager this one works!

**Comment by jonpugh** [comment]
Ran out of time to debug this.  Removing tests so we can have a clean release.

**Comment by arosboro** [comment]
Jon, I'm testing this branch in a local docker container.  I was able to get it to pass and install nginx after applying the changes in #99 i.e. remove --aegir-user-uid from the SCRIPT_OPTS in docker-development-environment.sh

I'm getting file permission issues such as:

```
TASK [opendevshop.devmaster : Install required drush packages.] ****************

failed: [devshop.docker] (item={'value': u'7.x-3.x', 'key': u'provision'}) => {"changed": true, "cmd": ["/usr/local/bin/drush", "dl", "provision-7.x-3.x", "--destination=/var/aegir/.drush/commands", "--package-handler=wget", "-y"], "delta": "0:00:00.442869", "end": "2016-05-08 14:37:24.350003", "failed": true, "item": {"key": "provision", "value": "7.x-3.x"}, "rc": 1, "start": "2016-05-08 14:37:23.907134", "stderr": " [error]  Destination directory /var/aegir/.drush/commands is not writable. ", "stdout": "", "stdout_lines": [], "warnings": []}

failed: [devshop.docker] (item={'value': u'7.x-2.2', 'key': u'registry_rebuild'}) => {"changed": true, "cmd": ["/usr/local/bin/drush", "dl", "registry_rebuild-7.x-2.2", "--destination=/var/aegir/.drush/commands", "--package-handler=wget", "-y"], "delta": "0:00:00.433652", "end": "2016-05-08 14:37:24.957859", "failed": true, "item": {"key": "registry_rebuild", "value": "7.x-2.2"}, "rc": 1, "start": "2016-05-08 14:37:24.524207", "stderr": " [error]  Destination directory /var/aegir/.drush/commands is not writable. ", "stdout": "", "stdout_lines": [], "warnings": []}

NO MORE HOSTS LEFT *************************************************************

RUNNING HANDLER [geerlingguy.nginx : reload nginx] *****************************

RUNNING HANDLER [geerlingguy.mysql : restart mysql] ****************************

RUNNING HANDLER [geerlingguy.php : restart webserver] **************************

RUNNING HANDLER [geerlingguy.php : restart php-fpm] ****************************
	to retry, use: --limit @playbook-nginx.retry

PLAY RECAP *********************************************************************
devshop.docker             : ok=97   changed=40   unreachable=0    failed=1  
```

resulting in:

```
   ____              ____  _
  |  _ \  _____   __/ ___|| |__   ___  _ __
  | | | |/ _ \ \ / /\___ \| '_ \ / _ \| '_ \
  | |_| |  __/\ V /  ___) | | | | (_) | |_) |
  |____/ \___| \_/  |____/|_| |_|\___/| .__/
           http://getdevshop.com      |_|  
╔═════════════════════════════════════════════╗
║                   Status                    ║
╚═════════════════════════════════════════════╝
Checking for DevShop CLI...  DevShop CLI is installed.  galaxy-roles 574a12a
Checking for Drush...  Drush is installed.  Drush Version   :  9.0-dev
Checking for Provision...  Provision not detected.
 [error]  Invalid command provision-save. 

Checking for DevMaster...  Devmaster not installed.
 [error]  Could not find the alias @hostmaster 

Devmaster site not detected.

The command 'devshop status' had an error. Check the logs and try again.
Stopping supervisor: supervisord.
 [error]  Could not find the alias @hostmaster 
Hostmaster alias not found.

NEXT: Please add '127.0.0.1 devshop.docker' to your /etc/hosts file.
 You must access the site at http://devshop.docker:8000 
 To get into the server, run: 
    $ docker exec -ti devshop_server su - aegir 
 Then to get into the front end, run:
    $ devshop login 
 You will get a URL like http://devshop.docker/user/login/13abc.  you will have to add the port 8000.
 Good luck! We hope to improve on this soon.  Please post issues at https://github.com/opendevshop/devshop/issues 
 
 NOTE: To run tests, we have disabled supervisor.  To run the task queue runner, run: 
 docker exec -ti devshop_server su - aegir -c 'drush @hostmaster en hosting_queued -y && drush @hostmaster hosting-queued' 
```

Stay tuned, I'll let you know if I find anything else.

**Comment by jonpugh** [comment]
Hmm, strange...

#99 has been merged for a while...

**Comment by jonpugh** [comment]
@arosboro Let's open up another PR for the NGINX work.

We really need another release so I'm just going with this for beta2

**Pull request merged**
