### PR TITLE
Improve install script and add tests for various install methods.

### PR DESCRIPTION
**Pull request by jonpugh**
- [x] Fix Install.sh: instability, bad versions, etc. Most of this was fixed in other PRs first.
  - [x] Ensure automatically detected server_hostname vars get devmaster installed correctly. (add a test to setup a server with a different hostname.)
  - [x] Add a scheduled job that runs the recommended install instructions.
  - [x] Remove playbook.yml, replace references to `roles/devshop.server/play.yml`
  - [x] The `/etc/ansible` isn't getting created when running manually.
  - [x]  Improve version management so PRs test the right version of devshop and developers 
  - [x] Git needs to be installed before anything else.
  - [x] opendevshop.users runs twice.
  - [x] The User UID/GID compare isn't working: User ID Change role gets triggered even though they appear to match. (commenting out for now)
  - [x] aegir_db_pass=root despite the install.sh file generating a password.
  - [x] Error:     Site installation caused an exception: https://github.com/opendevshop/devshop/pull/631/checks?check_run_id=1421193986#step:4:2385
    So so odd. Investigate differences in development and CI environments to determine cause.
  - [x] Write hostname value to file in /etc/ansible/host_vars. Devmaster is using AWS host name of ec2 instance for devmaster site. 
  - [x] Write server hostname to file in install.sh and 
    - [x] Put back  `--site={{ server_hostname }}` in devmaster:install command.
  - [x] Ansible Playbook host validation: `devshop-ansible-playbook` should exit 1 if no hosts are matched. 
  - [x] Fix inventory/play discrepancies with devshop.server vs devshop_server.
  - [ ] Implement LOAD_SCRIPT_COMMIT_SHA into the install script writer.
  - [ ] **MERGE THIS PR**

## Follow up Tasks

- [ ] Output the results of the makefile build to a test asset, and confirm proper var substitution.
- [ ] Ensure makefile build is writing the SHA correctly.
- [ ] Confirm deployment of the get.devshop.tech site with the new script.
- [ ] Create a schedule-only test of the get.devshop.tech install method.
- [ ] Confirm docker run instructions work: #635.
- [ ] Update installation instructions in getdevshop.com / gh-pages for install.sh, docker, docker-compose, and ansible.
- [ ] Update installation docs
- [ ] Add test jobs to install.yml for the officially supported install methods install.sh, docker, docker-compose, and ansible.
- [ ] Re-implement "Runtime" devshop tasks: Allow devshop to install as quickly as possible.

## Commit message

* Rewrite the standalone install.sh script emulating the https://get.docker.com install script. See https://github.com/docker/docker-install
* Add automated testing of the standalone install.sh script using a base container and a simple shell script to keep the system as generic as possible.
* Use a Makefile to process the install.sh script into an HTML file for get.devshop.tech:
  * Use env var substitution to write an install script with versions in it.
* Add functions to encapsulate logic like `get_distribution()` or `prepare_ubuntu1804`.
* Create small standard functions for installing prerequisites like pip and ansible.
* Improve the default static ansible inventory file.
* Use the `do_install` method so interrupted downloads don't break installation.
* Fix that crazy "drush: not found" and "devshop: not found" error during install script! no `backticks` in shell scripts!
* Use `devshop-ansible-playbook` in install.sh script so that the experience is as consistent as possible.
* Set composer library version to dev branches.

### CODE REVIEW

**Comment by matthandus** [comment]
Thanks for working on this!

**Comment by matthandus** [comment]
install.sh line 403 fails to write the file because the directory does not exist. Adding a mkdir command is a fix.
`mkdir $(dirname "${ANSIBLE_DEFAULT_HOST_LIST}")`
https://github.com/opendevshop/devshop/blob/11a8e18991f06add82d7e16c9691f4c11ab83ec3/install/install.sh#L403

**Comment by jonpugh** [comment]
The install.sh script now inherits the DEVSHOP_VERSION from the GitHub Actions metadata!

**Review by matthandus — CHANGES_REQUESTED** [review]
- [ ] Write hostname value to file in /etc/ansible/host_vars. Devmaster is using AWS host name of ec2 instance for devmaster site. Write server hostname to file in install.sh.

- [ ] Why is devshop control not installing?

**Review by matthandus — COMMENTED** [review]
Commands we ran to get devmaster profile to kick in.
`su - aegir`
`cd /var/aegir/devshop-control`
`composer config --global repo.devshop_devmaster {"path","/usr/share/devshop/devmaster"}
`
`composer reinstall`

**Comment by ichionid** [comment]
Run the script, popped up
**ERROR! Unexpected Exception, this is probably a bug: cannot import name 'AnsibleCollectionLoader'**

Trying to fix it in an ugly way.
```
prepare_ubuntu1804() {
  PYTHON_DEFAULT=/usr/bin/python3
  DEBIAN_FRONTEND=noninteractive
  apt-get update \
      && apt-get install -y --no-install-recommends \
         apt-utils \
         locales \
         python3-setuptools \
         python3-pip \
         software-properties-common \
         git \
      && rm -Rf /var/lib/apt/lists/* \
      && rm -Rf /usr/share/doc && rm -Rf /usr/share/man \
      && apt-get clean

  # Set Python3 to be the default (allow users to call "python" and "pip" instead of "python3" "pip3"
  update-alternatives --install /usr/bin/python python /usr/bin/python3 1
  pip3 uninstall ansible
  rm -rf /usr/local/lib/python3.7/site-packages/ansible
  pip3 install $pip_packages
}

```

Reference https://github.com/ansible-collections/community.kubernetes/issues/135

**Comment by jonpugh** [comment]
This is revealing some shortcomings of provision: https://github.com/opendevshop/devshop/pull/631/checks?check_run_id=1455818479#step:7:649

Composer install logs are not shown.  I think I fixed this but provision needs a release?

**Comment by jonpugh** [comment]
Force pushed because before todays work, CI was failing on devshop behat tests. 

Every test run today failed on install, way before testing. No idea why, cannot reproduce the "missing modules" bug

**Comment by jonpugh** [comment]
And yet, it's happening again.
https://github.com/opendevshop/devshop/pull/631/checks?check_run_id=1476200864#step:6:2545

**Comment by jonpugh** [comment]
Ohhh yaml. The install script writes an ansible inventory with `aegir_user_uid` as an INT, so maybe that's why it keeps going as an int there when it's a string most other places.

**Comment by jonpugh** [comment]
So odd.

DevShop Control is missing modules when installed via install.sh.

Test and build passes.

https://github.com/opendevshop/devshop/runs/1493723006#step:4:2337

This is the same odd behavior we saw in #632

**Pull request merged**
