### PR TITLE
Change PHP keywords to comply with PSR2

### PR DESCRIPTION
**Pull request by friendlydan**
Hi, I've changed some PHP keywords to comply with [this standard](https://www.php-fig.org/psr/psr-2/#25-keywords-and-truefalsenull) in PSR2. It's admittedly a small fix but I hope it helps!

### CODE REVIEW

**Comment by jonpugh** [comment]
There's a lot more code in the project than the Robofile. I'd prefer to clean it up all at once.

**Comment by Fonata** [comment]
As a project in the Drupal universe, I believe we should use the [Drupal coding standards](https://www.drupal.org/docs/develop/standards/coding-standards). Please specifically read the section "Constants".

My personal opinion is that this PR should be closed.

**Comment by jonpugh** [comment]
@Fonata Agreed. 

I also don't like that it was done by a bot, and not the PR author.

**Comment by jonpugh** [comment]
Besides, MOST of the PHP code is in  https://github.com/opendevshop/devmaster

**Pull request closed without merging**
