### PR TITLE
Added troubleshooting section to documentation

### PR DESCRIPTION
**Pull request by jdixon567**
I added a troubleshooting section to the Management section in the nav, including how to restart the queue runner.  Let me know if you feel troubleshooting should live elsewhere.

Also let me know if the formatting and the language is clear.  Thanks for the review!

### CODE REVIEW

**Comment by jonpugh** [comment]
`sudo service supervisor stop`

:wink:

Also, for the header, remove the backtick quotes. Those are typically used when you are referring to exact literal strings. I think you can format that as a regular sentence.

**Comment by jdixon567** [comment]
Oh man!  I added service in there for both commands.  It's late over here, but even later on the East coast so I don't have a good excuse.

Updated the formatting on that subheader too.  Thanks for havnig a look.

**Comment by jonpugh** [comment]
Beautiful. 

Thanks a ton, @jdixon567!  

Keep em comin. :rocket:

**Comment by jdixon567** [comment]
Glad I could help in a small way!  If I run into anything else that belongs in the documentation I will let you know and help get it in there.

**Pull request merged**
