### PR TITLE
Aegir 3! DevMaster in Drupal 7! Drupal 8 Hosting!

### PR DESCRIPTION
**Pull request by jonpugh**
See #30 for development task tracking.

### CODE REVIEW

**Comment by jonpugh** [comment]
Devmaster install works!

screenshot from 2016-01-22 16 02 25

**Comment by jonpugh** [comment]
So devshop installs, and I can login and start to create a project. I can get to the form where I specify environments.  When I submit that form, the whole server kindof dies.

Chrome gave me a "sad file" icon.
```
No data received

ERR_EMPTY_RESPONSE
ReloadHide details
Unable to load the webpage because the server sent no data.
```

`drush @hostmaster hosting-queued` is throwing `Segmentation fault (core dumped)`.

So strange.

**Comment by llwp** [comment]
wondering if apache returned any errors - /var/log/apache2/error.log ... are the symlinks created as well as the db entry?

**Comment by llwp** [comment]
deleted comment - just saw the details section of tests... is this right, it fails on php install?

**Comment by llwp** [comment]
:+1:

**Comment by llwp** [comment]
Version '5.5.9' for 'php5-fpm' was not found Action failed seems like a config issue...

**Comment by jonpugh** [comment]
In my local VM, once I submit the "environments" step of project create, the system goes sideways.

I can't even run `drush @hostmaster hosting-task`, which wouldn't do anything without a task NID:

```
aegir@devshop:~$ drush @hostmaster hosting-task
Segmentation fault (core dumped)
aegir@devshop:~$ drush @hostmaster hosting-task -v
Include /var/aegir/devmaster-1.x/profiles/devmaster/modules/aegir/hosting_logs/drush            [notice]
Include                                                                                         [notice]
/var/aegir/devmaster-1.x/profiles/devmaster/modules/aegir/hosting_site_backup_manager/drush
Include                                                                                         [notice]
/var/aegir/devmaster-1.x/profiles/devmaster/modules/aegir/hosting_tasks_extra/hosting_sync/drush
Include                                                                                         [notice]
/var/aegir/devmaster-1.x/profiles/devmaster/modules/aegir/hosting_tasks_extra/http_basic_auth/drush
Include /var/aegir/devmaster-1.x/profiles/devmaster/modules/aegir/hosting_tasks_extra/drush     [notice]
Include /var/aegir/devmaster-1.x/profiles/devmaster/modules/devshop/devshop_projects/drush      [notice]
Loaded alias @hostmaster from file /var/aegir/.drush/hostmaster.alias.drushrc.php               [notice]
Executing: mysql --defaults-extra-file=/tmp/drush_UB5Hgc --database=devshopsite --host=localhost --port=3306 --silent  < /tmp/drush_wtQkEk
Executing: mysql --defaults-extra-file=/tmp/drush_gcNIyV --database=devshopsite --host=localhost --port=3306 --silent  < /tmp/drush_NrDHU3
Segmentation fault (core dumped)
```

**Comment by jonpugh** [comment]
So close!

Ubuntu/Apache installed and the tests pass on travis: https://travis-ci.org/opendevshop/devshop/jobs/104831869

**Comment by jonpugh** [comment]
We switched to 1.x branch a few weeks ago.  

Never been happier to not merge a PR!

It was good knowing you, `0.x`.

**Pull request closed without merging**
